### PR TITLE
Include the 18F Vulnerability Disclosure Policy

### PR DESCRIPTION
**Pull request by adborden**
Resolves https://github.com/18F/open-source-policy/issues/20

### CODE REVIEW

**Comment by rahearn** [comment]
I'm wondering if this should be in `policy.md` in addition to (or instead of) `CONTRIBUTING.md`

**Comment by adborden** [comment]
The main reason it's in CONTRIBUTING is because this is the [template for all 18F projects](https://github.com/18f/18f-cli#license) and policy.md is not.

Should we have it in both places?

**Comment by rahearn** [comment]
That's a great reason to keep it in `CONTRIBUTING.md`.

I think it should be in `policy.md` because that's where the readme directs me to look after I found this repository some other way.

**Comment by bryanweast** [comment]
Threat Unclear hard to find *rocking back and forth 1 yr later*

**Review by Turist13vor — COMMENTED** [review]
notepad1614175888399
notepad1614175884906
[https://fotos](hydra)

**Pull request merged**
