### PR TITLE
Update contributing.md

### PR DESCRIPTION
**Pull request by andrewmaier**
@afeld

### CODE REVIEW

**Comment by afeld** [comment]
Hmm, I'm kinda :-1: on this, as it makes the raw markdown more difficult to read. Anyone else have strong feelings?

**Comment by benbalter** [comment]
Unless you're using that markdown elsewhere, and in a place that doesn't properly HTML-encode the output, I'm a fan of keeping markdown human-readable, and let machines do the heavy lifting at render time (which GitHub, Jekyll, etc. does, IIRC).

**Comment by konklone** [comment]
Yeah, I'm a :-1: on this as well. It's not worth complicating the raw form for smart quotes at render-time. I think it's a decision better made by the renderer itself. In theory, there's nothing stopping GitHub from rendering smart quotes for us from our non-smart-quoted Markdown.

**Comment by konklone** [comment]
I'm going to close, but if people would like to discuss/defend the PR further, feel free to re-open.

**Pull request closed without merging**
