### PR TITLE
swap his-or-her for their

### PR DESCRIPTION
**Pull request by janearc**
I use they as a pronoun, and noticed that this licence uses 'his or her' wording, so this pull request makes it easier for me to use the licence. It might also be worded *waiving all rights to the work* to avoid pronouns entirely.

### CODE REVIEW

**Comment by afeld** [comment]
Also, hope all is well 👋

**Comment by pkarman** [comment]
If this language comes from CC0 directly, then should we make PR upstream?

I'd be in favor of 
> It might also be worded waiving all rights to the work to avoid pronouns entirely.

since brevity is my watchword.

**Comment by konklone** [comment]
We should propose this upstream to CC, but without expecting that they'll take rapid action.

Note that this PR will only affect the summary of CC0, which isn't really the license. The formal CC license is here, and (unfortunately) uses "his or her" a few times:

https://creativecommons.org/publicdomain/zero/1.0/legalcode

I think we should continue to reference and use the CC0 license as written, but the text that we are in control of (the summary, and what we put in our LICENSE file) should reflect our intent and values. :+1: to the PR, as long as everyone understands it doesn't affect the actual legal licensing of the repository.

**Comment by konklone** [comment]
I filed https://github.com/18F/open-source-policy/pull/69 to make the change to `all rights`.

**Pull request merged**
