### PR TITLE
Integrate code of conduct into contributing document, tighten up intro a bit

### PR DESCRIPTION
**Pull request by konklone**
I updated `CONTRIBUTING.md` to link to our Code of Conduct. I also rearranged and rewrote some of the text, so that the welcome section was smaller and potentially less intimidating (especially since we're mentioning a set of rules now).

This would become our new boilerplate `CONTRIBUTING.md` for 18F projects. We could follow up this PR with individual project PRs, if folks are motivated.

### CODE REVIEW

**Comment by jeremiak** [comment]
Looks great to me! The welcome language is friendlier and including the Code of Conduct is :+1: 

I'm willing to help submit project PRs once we merge this @konklone

**Comment by konklone** [comment]
OK, merged it in!

cc @annalee @jackiekazil @ultrasaurus @leahbannon

**Comment by jackiekazil** [comment]
:+1:

**Comment by leahbannon** [comment]
:+1: :+1: :+1:

**Pull request merged**
